### ISSUE TITLE
History seems to be adding one too many tokens

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#25] opened 2016-01-26 20:25 UTC
```text
nm-subscriber> show session apn all
nm-subscriber ...> ?
Show sessions for all APNs.

count    Show session counts for all APNs.
nm-subscriber ...> count
500 - NGINX or PostgreSQL error, see log files for more details
<up key>
nm-subscriber ...> all count
all count
    ^ Parse error.
nm-subscriber ...> 
```

**Comment by alandekok** [comment] 2016-01-27 00:38
This seems fixed now.  I can't reproduce it.

**Closed** 2016-01-27 14:55 UTC
